services:
  traefik:
    image: traefik
    container_name: traefik
    restart: always
    command:
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - network-traefik # With this network, all services can communicate to traefik

networks:
  network-traefik:
    external: true